[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = """\
default-src 'self'; \
img-src 'self'; \
script-src 'self'; \
style-src 'self' 'unsafe-inline'; \
frame-ancestors 'self'; \
"""

[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"

[[redirects]]
from = "/p/js/script.js"
to = "https://plausible.io/js/script.js"
status = 200

[[redirects]]
from = "/p/api/event"
to = "https://plausible.io/api/event"
status = 200

[[redirects]]
from = "/p/api/event"
to = "https://plausible.io/api/event"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
publish = "dist"
command = "npm run build"
